### ISSUE TITLE
Validate `create_data`

### ISSUE THREAD

**Issue by zouharvi** [zouharvi/MosQEto#30]
At this point, the `create_data.yaml` file got quite complex. It should be validated that it does what we want it to do.

```
---
dataset_load:
  - "wmt19/en-de"
  - "opus/tech/en-de"
  - "custom/data_tmp"

dataset_save: 
  - "data_tmp/"
  - "data_all/"

method:
  # load WMT19, supersample, save to data_tmp/
  - print:Supersampling and expanding PE from WMT19
  - Loader:load
  - DataUtils:info
  - Generator:expand_post_edited
  - Generator:supersample:4
  - DataUtils:info
  - Loader:save
  - Loader:flush

  # loads the OPUS data
  - print:Generating from OPUS
  - Loader:load:noalign
  - Generator:generate
  - DataUtils:info

  # load the other data and mix them together
  - print:Mixing together
  - Loader:load
  - Generator:mix
  - DataUtils:info

  # take only gap data
  # - DataUtils:gap_only
  - Loader:save

generator:
  remove_prob: 0.05
  add_unigram_prob: 0.05
  change_unigram_prob: 0.05
```
